export const SYSTEM_SAGA_ACTIONS = {
  SET_SYSTEM_INIT: "SET_SYSTEM_INIT",
  SET_LOGIN: "SET_LOGIN",
  SET_LOGOUT: "SET_LOGOUT",
  JUST_LOGOUT: "JUST_LOGOUT",
  SET_AUTHORIZATION: "SET_AUTHORIZATION",
  SET_AVAILABLE_SERVICES: "SET_AVAILABLE_SERVICES",
  SET_USER_INFO_BY_ID: "SET_USER_INFO_BY_ID"
};
