export const NavKeys = {
  // Common stack
  COMING_SOON: "COMING_SOON",
  MY_PROFILE: "MY_PROFILE",

  // OnBoard stack
  ONBOARD_STEP1: "ONBOARD_STEP1",
  ONBOARD_STEP2: "ONBOARD_STEP2",
  ONBOARD_STEP3: "ONBOARD_STEP3",

  // Auth stack
  AUTH_WELCOME: "AUTH_WELCOME",
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_FORCE_CHANGE_PASSWORD: "AUTH_FORCE_CHANGE_PASSWORD",
  AUTH_FORGOT_PASSWORD: "AUTH_FORGOT_PASSWORD",
  AUTH_OTP_VALIDATION: "AUTH_OTP_VALIDATION",

  ADMIN: {
    PERMISSION_SCREEN: "PERMISSION_SCREEN",
    PERMISSION_FORM: "PERMISSION_FORM",
    PERMISSION_GROUP_SCREEN: "PERMISSION_GROUP_SCREEN",
    PERMISSION_GROUP_FORM: "PERMISSION_GROUP_FORM",
    ROLE_SCREEN: "ROLE_SCREEN",
    ROLE_FORM: "ROLE_FORM",
    USER_LIST: "USER_LIST",
    MANAGE_CATEGORIES_SCREEN: "MANAGE_CATEGORIES_SCREEN",
    MANAGE_CATEGORIES_FORM: "MANAGE_CATEGORIES_FORM",
    MANAGE_SERVICES_SCREEN: "MANAGE_SERVICES_SCREEN",
    MANAGE_SERVICES_FORM: "MANAGE_SERVICES_FORM",
    // user onboarding
    USER_ONBOARDING_WELCOME: "USER_ONBOARDING_WELCOME",
    USER_ONBOARDING_USER: "USER_ONBOARDING_USER",
    USER_ONBOARDING_BUSINESS: "USER_ONBOARDING_BUSINESS",
    USER_ONBOARDING_BANK: "USER_ONBOARDING_BANK",
    USER_ONBOARDING_ADDRESS: "USER_ONBOARDING_ADDRESS",
    USER_ONBOARDING_SUPPORTING_DOCS: "USER_ONBOARDING_SUPPORTING_DOCS",
    USER_ONBOARDING_SUPPORTING_DOCS_LIST:
      "USER_ONBOARDING_SUPPORTING_DOCS_LIST",
  },

  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  WALLET: {
    REFILL_OPTIONS: "REFILL_OPTIONS",
    CASH_DEPOSIT: "CASH_DEPOSIT",
    CASH_DEPOSIT_FORM: "CASH_DEPOSIT_FORM",
    RAZOR_PAY: "RAZOR_PAY",
    RAZOR_PAY_FORM: "RAZOR_PAY_FORM",
  },

  // App - Common Stack
  TAB_DASHBOARD: {
    NAME: "TAB_DASHBOARD",
    TAB_SCREEN_CONSOLE: "TAB_SCREEN_CONSOLE",
    TAB_SCREEN_CATEGORY: "TAB_SCREEN_CATEGORY",
    TAB_SCREEN_HOME: "TAB_SCREEN_HOME",
    TAB_SCREEN_WALLET: "TAB_SCREEN_WALLET",
    TAB_SCREEN_FORUM: "TAB_SCREEN_FORUM",
  },

  //PROFILE PAGE
  PROFILE: {
    USER_DETAILS: "USER_DETAILS",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    LANGUAGES: "LANGUAGES",
    NOTIFICATIONS: "NOTIFICATIONS",
  },

  //SERVICE FORMS
  FormData: {
    GST_FILING: "GST_FILING",
    GST_REGISTRATION: "GST_REGISTRATION",
    MSME_REGISTRATION: "MSME_REGISTRATION",
    FSSAI_REGISTRATION: "FSSAI_REGISTRATION",
    TRADEMARK_AND_COPYRIGHTS: "TRADEMARK_AND_COPYRIGHTS",
    WEB_DEVELOPMENT: "WEB_DEVELOPMENT",
    SOFTWARES: "SOFTWARES",
    DIGITAL_MARKETING: "DIGITAL_MARKETING",
    ISO_SERVICES: "ISO_SERVICES",
    TAN_ALLOTMENT: "TAN_ALLOTMENT",
    DIGITAL_SIGNATURE: "DIGITAL_SIGNATURE",
    PARTNERSHIP_FIRM_REGISTRATION: "PARTNERSHIP_FIRM_REGISTRATION",
    IMPORT_EXPORT_LICENCE: "IMPORT_EXPORT_LICENCE",
    COMPANY_INCORPORATION: "COMPANY_INCORPORATION",
    ITR_FILING_SALARIED: "ITR_FILING_SALARIED",
    ITR_FILING_BUSINESS: "ITR_FILING_BUSINESS",
    PAN_REGISTRATION: "PAN_REGISTRATION",
  },

  // App - Service Stack
  SERVICES: {
    ONBOARDING_PURCHASE: "ONBOARDING_PURCHASE",
  },
  RECHARGE_MOBILE: "RECHARGE_MOBILE",
  RECHARGE_MOBILE_HISTORY: "RECHARGE_MOBILE_HISTORY",
  RECHARGE_SELECTPLAN: "RECHARGE_SELECTPLAN",
  RECHARGE_CONFIRM: "RECHARGE_CONFIRM",
  PDF_MANAGEMENT: "PDF_MANAGEMENT",
  RECHARGE_SETTINGS: "RECHARGE_SETTINGS",
  RECHARGE_OPERATOR_FORM: "RECHARGE_OPERATOR_FORM",
  RECHARGE_PROVIDER_FORM: "RECHARGE_PROVIDER_FORM",
  RECHARGE_COMMISSION_FORM: "RECHARGE_COMMISSION_FORM"
};

export const serviceNavigationKeyOptions = [
  { key: "ONBOARDING_PURCHASE", name: "ONBOARDING PURCHASE" },
  { key: "RECHARGE_MOBILE", name: "RECHARGE MOBILE" },
  { key: "GST_FILING", name: "GST Filling" },
  { key: "GST_REGISTRATION", name: "GST Registration" },
  { key: "MSME_REGISTRATION", name: "Msme Registration" },
  { key: "FSSAI_REGISTRATION", name: "Fssai Registration" },
  { key: "TRADEMARK_AND_COPYRIGHTS", name: "Trademark & Copyrights" },
  { key: "WEB_DEVELOPMENT", name: "Web Development" },
  { key: "SOFTWARES", name: "Softwares" },
  { key: "DIGITAL_MARKETING", name: "Digital Marketing" },
  { key: "ISO_SERVICES", name: "Iso Services" },
  { key: "TAN_ALLOTMENT", name: "Tan Allotment" },
  { key: "DIGITAL_SIGNATURE", name: "Digital Signature" },
  { key: "PARTNERSHIP_FIRM_REGISTRATION", name: "Partnership Firm Registration" },
  { key: "IMPORT_EXPORT_LICENCE", name: "Import Export Licence" },
  { key: "COMPANY_INCORPORATION", name: "Company Incorporation" },
  { key: "ITR_FILING_SALARIED", name: "ITR Filing Salaried" },
  { key: "ITR_FILING_BUSINESS", name: "ITR Filing Business" },
  { key: "PAN_REGISTRATION", name: "PAN Registration" },

];
