export const SYSTEM_SAGA_ACTIONS = {
  SET_BALANCE_TRANSACTION: "SET_BALANCE_TRANSACTION",
  SET_CASH_DEPOSIT: "SET_CASH_DEPOSIT",
  TRANSACT_CASH_DEPOSIT: "TRANSACT_CASH_DEPOSIT",
  TRANSACT_RAZOR_PAY: "TRANSACT_RAZOR_PAY"
};
