export const ADMIN_SAGA_ACTIONS = {
  SET_ADDRESS_OPTIONS: "SET_ADDRESS_OPTIONS",
  SET_RBAC_OPTIONS: "SET_RBAC_OPTIONS",
  SET_PERMISSION_OPTIONS: "SET_PERMISSION_OPTIONS",
  SET_PERMISSION_GROUP_OPTIONS: "SET_PERMISSION_GROUP_OPTIONS",
  SET_ROLE_OPTIONS: "SET_ROLE_OPTIONS",
};
